#!/bin/bash
# yoinkit research "<topic>" [options]
# Automated research workflow

set -e

TOPIC="$1"
shift || true

# Parse options
PLATFORMS="youtube,tiktok,twitter"
DEPTH="normal"
TRANSCRIPTS=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --platforms)
            PLATFORMS="$2"
            shift 2
            ;;
        --depth)
            DEPTH="$2"
            shift 2
            ;;
        --transcripts)
            TRANSCRIPTS=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

if [ -z "$TOPIC" ]; then
    echo "Error: Topic required"
    echo "Usage: yoinkit research \"<topic>\" [--platforms LIST] [--depth MODE] [--transcripts]"
    exit 1
fi

if [ -z "$YOINKIT_API_TOKEN" ]; then
    echo "Error: YOINKIT_API_TOKEN not configured"
    exit 1
fi

API_BASE="${YOINKIT_API_URL:-https://yoinkit.com/api/v1/openclaw}"
SCRIPT_DIR="$(dirname "$0")"

echo "# Research Report: $TOPIC"
echo ""
echo "**Platforms:** $PLATFORMS"
echo "**Depth:** $DEPTH"
echo "**Generated:** $(date '+%Y-%m-%d %H:%M')"
echo ""

# Set limits based on depth
case "$DEPTH" in
    quick)
        SEARCH_LIMIT=5
        TRENDING_LIMIT=5
        ;;
    deep)
        SEARCH_LIMIT=20
        TRENDING_LIMIT=20
        ;;
    *)
        SEARCH_LIMIT=10
        TRENDING_LIMIT=10
        ;;
esac

# Process each platform
IFS=',' read -ra PLATFORM_ARRAY <<< "$PLATFORMS"
for PLATFORM in "${PLATFORM_ARRAY[@]}"; do
    echo "## $PLATFORM"
    echo ""
    
    # Search
    echo "### Search Results"
    SEARCH_RESPONSE=$(curl -s -H "Authorization: Bearer $YOINKIT_API_TOKEN" \
        "$API_BASE/$PLATFORM/search?query=$(echo "$TOPIC" | jq -sRr @uri)&limit=$SEARCH_LIMIT")
    
    if echo "$SEARCH_RESPONSE" | jq -e '.success == true' > /dev/null 2>&1; then
        echo "$SEARCH_RESPONSE" | jq -r '.data.results[]? | "- \(.title // .text // .description | .[0:80])... (\(.views // .likes // 0) engagement)"' 2>/dev/null || echo "No results"
    else
        echo "Search unavailable"
    fi
    echo ""
    
    # Trending (if available for platform)
    echo "### Trending"
    TRENDING_RESPONSE=$(curl -s -H "Authorization: Bearer $YOINKIT_API_TOKEN" \
        "$API_BASE/$PLATFORM/trending?limit=$TRENDING_LIMIT")
    
    if echo "$TRENDING_RESPONSE" | jq -e '.success == true' > /dev/null 2>&1; then
        echo "$TRENDING_RESPONSE" | jq -r '.data.trending[]? | "- \(.title // .name // .text | .[0:80])..."' 2>/dev/null | head -5 || echo "No trending data"
    else
        echo "Trending unavailable"
    fi
    echo ""
done

# Deep mode: pull transcripts
if [ "$DEPTH" = "deep" ] && [ "$TRANSCRIPTS" = true ]; then
    echo "## Transcript Analysis"
    echo ""
    echo "*Deep transcript analysis would be performed here.*"
    echo "*Pull top 3-5 video transcripts and summarize key themes.*"
    echo ""
fi

echo "---"
echo "*Report generated by yoinkit-social skill*"
